import Head from "next/head";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>Grocer | Go</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.png" />
        </Head>
        {/* body */}
        <main>
          <h1>Hello from Grossy</h1>        
        </main>
      </div>
    </Layout>
  );
}
