import Head from "next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Services from "../components/Services"
import css from "../styles/Home.module.css"

const  Home = () => {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>Grocer | Go</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero /> 
          <Services />       
        </main>
      </div>
    </Layout>
  );
}
export default Home;
